


server:
  port: 80
  address: localhost


spring:
  thymeleaf:
    cache: false
    #热部署静态文件
    encoding: UTF-8
    mode: HTML5
  h2:
    console:
      #开始H2内存数据库
      enabled: true
  # DataSource
  datasource:
    url: jdbc:mysql://localhost/blog?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #JPA
  jpa:
    #项目运行时，会打印sql语句
    show-sql: true
    #create-drop是指每次应用启动时，都会自动删除并创建数据库表，
    #hibernate:
      #ddl-auto: create-drop
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
#使用本地的mongodb的时候才配置mongodb的uri
#    mongodb:
#      uri: mongodb://localhost:27017/test
file:
  server:
    url: http://localhost:8081/upload

